### PR TITLE
Add an async streams status quo for Barbara

### PR DESCRIPTION
**Pull request by jonathandturner**
This adds a status quo story for Barbara based on our experience using async streams in Nushell.

### CODE REVIEW

**Review by rylev — COMMENTED** [review]
This is definitely a very interesting story - Thank you! It certainly has a bit of overlap with #48. I wonder what if we can reword the morals in light of #48 existing so we have a clear take-away from this story other than what is already covered in #48.

**Comment by nikomatsakis** [comment]
@jonathandturner that sounds helpful (using summary as morals)

**Comment by jonathandturner** [comment]
Updated

**Comment by nikomatsakis** [comment]
Thanks @jonathandturner!

**Review by rylev — APPROVED** [review]
Awesome! I think this really highlights the issues of *using* streams where as the other stream story we have is about *creating* streams. Really great!

**Pull request merged**
