### PR TITLE
integrate new character axes and applications

### PR DESCRIPTION
**Pull request by nikomatsakis**
Update content somewhat, integrating the idea of character axes and applications.

Rendered form: https://nikomatsakis.github.io/wg-async-foundations/

### CODE REVIEW

**Comment by tmandry** [comment]
I don't think you meant to commit all these rendered files?

**Comment by tmandry** [comment]
I think we should keep these as short and to the point as possible. Here's a draft for operating systems:

> Core system services like filesystems and networking. IPC between various programs and services. Kernel and driver code; waiting on device I/O.
> - What separates this from others?
>     - Latency profile: Typically 100's-1,000's of ns, uncontended, for IPC

Since the list is kind of long maybe we should only keep skeletons around for the ones we _know_ we want and include a list of bullet points at the end for skimming.

I think database servers and high-performance I/O are redundant.

**Comment by nikomatsakis** [comment]
@tmandry I did not mean to commit rendered files, it's true :)

Also, I agree the list is long. I like the idea of having a few with short descriptions, and a bullet, and encouraging folks to turn them into something more real.

**Comment by nikomatsakis** [comment]
I've reworked the presentation of the axes to emphasize the characters more. I think it was kind of overwhelming before.

**Comment by nikomatsakis** [comment]
Gonna merge this so we can keep iterating =)

**Pull request merged**
