### PR TITLE
second draft of vision doc process

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is my second take at laying out the structure of the vision document. It's a bit more expansive than the first try. I included a bunch of proposed section headings for things that I think should be part of it, but it's worth emphasizing that these are partly just guesses. In some cases I included assignees -- these are brave souls that I have volunteered to try and elaborate some of the sections. 

Love to hear what people think. If you want to see the vision doc in rendered form, [you can find it on my fork](https://nikomatsakis.github.io/wg-async-foundations/vision.html).

### CODE REVIEW

**Comment by taiki-e** [comment]
Is it possible to separate parts not related to vision doc (`src/vision`) into separate PR? (Changes on existing docs, layout changes, triage docs, etc.)
The current PR includes various changes, and I think the separation will make the diff easier to read. (If it is difficult to separate or it takes time, I'm okay with leaving it as it is.)

(I like this PR's changes to the existing docs, but I don't have time to read/review the vision docs.)

**Comment by bIgBV** [comment]
One thing that I feel could be improved is that "startup developer" persona. There's a lot of engineers working on services which are not giant orgs, and neither are they working in smaller startups building a single product. Either the "startup developer" persona should change to "service engineer" or there should be a separate persona. The concerns for both are fairly similar I think, in that they want to be able to deploy a rust based web service. Therefore, I think the "startup persona" should be expanded to include this.

**Comment by nikomatsakis** [comment]
@bIgBV good feedback! it sounds like maybe you are volunteering to help me tweak those characters! I'd love to learn more about the details here. Actually, you're giving me an idea -- I think that the characters should have FAQs too, to help elaborate what things they find most important. I'm going to try and add that.

**Review by tmandry — APPROVED** [review]
Haven't gotten to review this in detail yet, but overall it looks good. I'm fine with merging and iterating from there.

**Comment by nikomatsakis** [comment]
OK, so, I added some more provisos to indicate that everything in here is in draft, and that this is a WIP. I'm going to go ahead and merge this so that people can start to open PRs to add and change things. I want to re-iterate that if you are interested or have ideas for improvement (e.g., missing stories, things you want to write, etc), please ping me.

**Pull request merged**
