### PR TITLE
Add life of a Facebook C++ engineer status quo story

### PR DESCRIPTION
**Pull request by metajack**
This is currently an outline, similar in style to @nikomatsakis's life of an AWS engineer story.

### CODE REVIEW

**Comment by metajack** [comment]
cc @pcwalton @bmwill who may have some feedback and suggestions

**Comment by eminence** [comment]
The outline for the story seems pretty sensible in terms of what Grace would actually need to do, but it all seems to be generic rust stuff.  Where in this outline do you see async challenges coming into this story?

**Comment by nikomatsakis** [comment]
I'm interested in both sync and async, whatever is effect peopling trying to build systems on async Rust.

**Comment by nikomatsakis** [comment]
I'm going to merge, we can always add more details in subsequent PRs.

**Pull request merged**
